[files]
extend-exclude = [
    ".git/",
    "src/Model/Country.php",
]
ignore-hidden = false

[default]
extend-ignore-re = [
]

[default.extend-words]
# Typos in Billingo spec
# read (past tense)
"readed" = "readed"

[default.extend-identifiers]
"NAM_1" = "NAM_1"
"NAM_2" = "NAM_2"
"PICK_PACK_PONT" = "PICK_PACK_PONT"
"pick_pack_pont" = "pick_pack_pont"
