<?php

/**
 * CheckTaxNumberMessage
 *
 * PHP version 8.1
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billingo API v3
 *
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\Billingo\Model;

/**
 * CheckTaxNumberMessage Class Doc Comment
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum CheckTaxNumberMessage: string
{
    case EXTERNAL_NAV_SERVICE_UNREACHABLE = 'external_nav_service_unreachable';

    case INVALID_TAX_NUMBER = 'invalid_tax_number';

    case NO_ONLINE_SZAMLA_SETTINGS = 'no_online_szamla_settings';

    case NON_EXIST_TAX_NUMBER = 'non_exist_tax_number';

    case VALIDATION_OK = 'validation_ok';
}
