<?php

/**
 * Currency
 *
 * PHP version 8.1
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billingo API v3
 *
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\Billingo\Model;

/**
 * Currency Class Doc Comment
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum Currency: string
{
    case AED = 'AED';

    case AUD = 'AUD';

    case BGN = 'BGN';

    case BRL = 'BRL';

    case CAD = 'CAD';

    case CHF = 'CHF';

    case CNY = 'CNY';

    case CZK = 'CZK';

    case DKK = 'DKK';

    case EUR = 'EUR';

    case GBP = 'GBP';

    case HKD = 'HKD';

    case HRK = 'HRK';

    case HUF = 'HUF';

    case IDR = 'IDR';

    case ILS = 'ILS';

    case INR = 'INR';

    case ISK = 'ISK';

    case JPY = 'JPY';

    case KRW = 'KRW';

    case MXN = 'MXN';

    case MYR = 'MYR';

    case NOK = 'NOK';

    case NZD = 'NZD';

    case PHP = 'PHP';

    case PLN = 'PLN';

    case RON = 'RON';

    case RSD = 'RSD';

    case RUB = 'RUB';

    case SEK = 'SEK';

    case SGD = 'SGD';

    case THB = 'THB';

    case _TRY = 'TRY';

    case UAH = 'UAH';

    case USD = 'USD';

    case ZAR = 'ZAR';
}
