<?php

/**
 * Feature
 *
 * PHP version 8.1
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billingo API v3
 *
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\Billingo\Model;

/**
 * Feature Class Doc Comment
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum Feature: string
{
    case API_LIMIT_BASIC = 'api_limit_basic';

    case API_LIMIT_PRO = 'api_limit_pro';

    case API_LIMIT_STANDARD = 'api_limit_standard';

    case BANKSYNC_PLUS = 'banksync_plus';

    case CAMPAIGN_MANAGER_BASIC = 'campaign_manager_basic';

    case CAMPAIGN_MANAGER_STANDARD = 'campaign_manager_standard';

    case CEGINFO_ENTERPRISE = 'ceginfo_enterprise';

    case CEGINFO_PRO = 'ceginfo_pro';

    case CEGINFO_STANDARD = 'ceginfo_standard';

    case INNOVATOR = 'innovator';

    case LIMIT_INCREASE = 'limit_increase';

    case MASTER = 'master';

    case PARTNERMONITOR_BASIC = 'partnermonitor_basic';

    case PARTNERMONITOR_PRO = 'partnermonitor_pro';

    case PARTNERMONITOR_STANDARD = 'partnermonitor_standard';

    case SOFTPOS = 'softpos';

    case SUBSCRIPTION_BASIC = 'subscription_basic';

    case SUBSCRIPTION_PRO = 'subscription_pro';

    case SUBSCRIPTION_STANDARD = 'subscription_standard';

    case TENDERMONITOR_STANDARD = 'tendermonitor_standard';

    case TENDERMONITOR_VIP = 'tendermonitor_vip';

    case WHITELABEL = 'whitelabel';
}
