<?php

/**
 * PaymentMethod
 *
 * PHP version 8.1
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billingo API v3
 *
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\Billingo\Model;

/**
 * PaymentMethod Class Doc Comment
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum PaymentMethod: string
{
    case ARUHITEL = 'aruhitel';

    case BANKCARD = 'bankcard';

    case BARION = 'barion';

    case BARTER = 'barter';

    case CASH = 'cash';

    case CASH_ON_DELIVERY = 'cash_on_delivery';

    case COUPON = 'coupon';

    case ELORE_UTALAS = 'elore_utalas';

    case EP_KARTYA = 'ep_kartya';

    case KOMPENZACIO = 'kompenzacio';

    case LEVONAS = 'levonas';

    case ONLINE_BANKCARD = 'online_bankcard';

    case OTHER = 'other';

    case PAYLIKE = 'paylike';

    case PAYONEER = 'payoneer';

    case PAYPAL = 'paypal';

    case PAYPAL_UTOLAG = 'paypal_utolag';

    case PAYU = 'payu';

    case PICK_PACK_PONT = 'pick_pack_pont';

    case POSTAI_CSEKK = 'postai_csekk';

    case POSTAUTALVANY = 'postautalvany';

    case SKRILL = 'skrill';

    case SZEP_CARD = 'szep_card';

    case TRANSFERWISE = 'transferwise';

    case UPWORK = 'upwork';

    case UTALVANY = 'utalvany';

    case VALTO = 'valto';

    case WIRE_TRANSFER = 'wire_transfer';
}
