<?php
/**
 * DocumentExportFilterExtra
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Cone\Billingo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billingo API v3
 *
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.15
 * Contact: hello@billingo.hu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\Billingo\Model;

use \ArrayAccess;
use \Cone\Billingo\ObjectSerializer;

/**
 * DocumentExportFilterExtra Class Doc Comment
 *
 * @category Class
 * @package  Cone\Billingo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DocumentExportFilterExtra implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DocumentExportFilterExtra';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tensoft_vkod' => 'string',
        'ledger_number' => '\Cone\Billingo\Model\LedgerNumberInformation',
        'forintsoft_konyvelesi_naplo_szam' => 'string',
        'positive_ledger_number' => 'string',
        'negative_ledger_number' => 'string',
        'rlb_kata' => 'bool',
        'rlb_note' => 'string',
        'novitax_naplokod' => 'string',
        'use_gross_values' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tensoft_vkod' => null,
        'ledger_number' => null,
        'forintsoft_konyvelesi_naplo_szam' => null,
        'positive_ledger_number' => null,
        'negative_ledger_number' => null,
        'rlb_kata' => null,
        'rlb_note' => null,
        'novitax_naplokod' => null,
        'use_gross_values' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tensoft_vkod' => false,
		'ledger_number' => false,
		'forintsoft_konyvelesi_naplo_szam' => false,
		'positive_ledger_number' => false,
		'negative_ledger_number' => false,
		'rlb_kata' => false,
		'rlb_note' => false,
		'novitax_naplokod' => false,
		'use_gross_values' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tensoft_vkod' => 'tensoft_vkod',
        'ledger_number' => 'ledger_number',
        'forintsoft_konyvelesi_naplo_szam' => 'forintsoft_konyvelesi_naplo_szam',
        'positive_ledger_number' => 'positive_ledger_number',
        'negative_ledger_number' => 'negative_ledger_number',
        'rlb_kata' => 'rlb_kata',
        'rlb_note' => 'rlb_note',
        'novitax_naplokod' => 'novitax_naplokod',
        'use_gross_values' => 'use_gross_values'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tensoft_vkod' => 'setTensoftVkod',
        'ledger_number' => 'setLedgerNumber',
        'forintsoft_konyvelesi_naplo_szam' => 'setForintsoftKonyvelesiNaploSzam',
        'positive_ledger_number' => 'setPositiveLedgerNumber',
        'negative_ledger_number' => 'setNegativeLedgerNumber',
        'rlb_kata' => 'setRlbKata',
        'rlb_note' => 'setRlbNote',
        'novitax_naplokod' => 'setNovitaxNaplokod',
        'use_gross_values' => 'setUseGrossValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tensoft_vkod' => 'getTensoftVkod',
        'ledger_number' => 'getLedgerNumber',
        'forintsoft_konyvelesi_naplo_szam' => 'getForintsoftKonyvelesiNaploSzam',
        'positive_ledger_number' => 'getPositiveLedgerNumber',
        'negative_ledger_number' => 'getNegativeLedgerNumber',
        'rlb_kata' => 'getRlbKata',
        'rlb_note' => 'getRlbNote',
        'novitax_naplokod' => 'getNovitaxNaplokod',
        'use_gross_values' => 'getUseGrossValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('tensoft_vkod', $data ?? [], null);
        $this->setIfExists('ledger_number', $data ?? [], null);
        $this->setIfExists('forintsoft_konyvelesi_naplo_szam', $data ?? [], null);
        $this->setIfExists('positive_ledger_number', $data ?? [], null);
        $this->setIfExists('negative_ledger_number', $data ?? [], null);
        $this->setIfExists('rlb_kata', $data ?? [], null);
        $this->setIfExists('rlb_note', $data ?? [], null);
        $this->setIfExists('novitax_naplokod', $data ?? [], null);
        $this->setIfExists('use_gross_values', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tensoft_vkod
     *
     * @return string|null
     */
    public function getTensoftVkod()
    {
        return $this->container['tensoft_vkod'];
    }

    /**
     * Sets tensoft_vkod
     *
     * @param string|null $tensoft_vkod tensoft_vkod
     *
     * @return self
     */
    public function setTensoftVkod($tensoft_vkod)
    {
        if (is_null($tensoft_vkod)) {
            throw new \InvalidArgumentException('non-nullable tensoft_vkod cannot be null');
        }
        $this->container['tensoft_vkod'] = $tensoft_vkod;

        return $this;
    }

    /**
     * Gets ledger_number
     *
     * @return \Cone\Billingo\Model\LedgerNumberInformation|null
     */
    public function getLedgerNumber()
    {
        return $this->container['ledger_number'];
    }

    /**
     * Sets ledger_number
     *
     * @param \Cone\Billingo\Model\LedgerNumberInformation|null $ledger_number ledger_number
     *
     * @return self
     */
    public function setLedgerNumber($ledger_number)
    {
        if (is_null($ledger_number)) {
            throw new \InvalidArgumentException('non-nullable ledger_number cannot be null');
        }
        $this->container['ledger_number'] = $ledger_number;

        return $this;
    }

    /**
     * Gets forintsoft_konyvelesi_naplo_szam
     *
     * @return string|null
     */
    public function getForintsoftKonyvelesiNaploSzam()
    {
        return $this->container['forintsoft_konyvelesi_naplo_szam'];
    }

    /**
     * Sets forintsoft_konyvelesi_naplo_szam
     *
     * @param string|null $forintsoft_konyvelesi_naplo_szam forintsoft_konyvelesi_naplo_szam
     *
     * @return self
     */
    public function setForintsoftKonyvelesiNaploSzam($forintsoft_konyvelesi_naplo_szam)
    {
        if (is_null($forintsoft_konyvelesi_naplo_szam)) {
            throw new \InvalidArgumentException('non-nullable forintsoft_konyvelesi_naplo_szam cannot be null');
        }
        $this->container['forintsoft_konyvelesi_naplo_szam'] = $forintsoft_konyvelesi_naplo_szam;

        return $this;
    }

    /**
     * Gets positive_ledger_number
     *
     * @return string|null
     */
    public function getPositiveLedgerNumber()
    {
        return $this->container['positive_ledger_number'];
    }

    /**
     * Sets positive_ledger_number
     *
     * @param string|null $positive_ledger_number positive_ledger_number
     *
     * @return self
     */
    public function setPositiveLedgerNumber($positive_ledger_number)
    {
        if (is_null($positive_ledger_number)) {
            throw new \InvalidArgumentException('non-nullable positive_ledger_number cannot be null');
        }
        $this->container['positive_ledger_number'] = $positive_ledger_number;

        return $this;
    }

    /**
     * Gets negative_ledger_number
     *
     * @return string|null
     */
    public function getNegativeLedgerNumber()
    {
        return $this->container['negative_ledger_number'];
    }

    /**
     * Sets negative_ledger_number
     *
     * @param string|null $negative_ledger_number negative_ledger_number
     *
     * @return self
     */
    public function setNegativeLedgerNumber($negative_ledger_number)
    {
        if (is_null($negative_ledger_number)) {
            throw new \InvalidArgumentException('non-nullable negative_ledger_number cannot be null');
        }
        $this->container['negative_ledger_number'] = $negative_ledger_number;

        return $this;
    }

    /**
     * Gets rlb_kata
     *
     * @return bool|null
     */
    public function getRlbKata()
    {
        return $this->container['rlb_kata'];
    }

    /**
     * Sets rlb_kata
     *
     * @param bool|null $rlb_kata rlb_kata
     *
     * @return self
     */
    public function setRlbKata($rlb_kata)
    {
        if (is_null($rlb_kata)) {
            throw new \InvalidArgumentException('non-nullable rlb_kata cannot be null');
        }
        $this->container['rlb_kata'] = $rlb_kata;

        return $this;
    }

    /**
     * Gets rlb_note
     *
     * @return string|null
     */
    public function getRlbNote()
    {
        return $this->container['rlb_note'];
    }

    /**
     * Sets rlb_note
     *
     * @param string|null $rlb_note rlb_note
     *
     * @return self
     */
    public function setRlbNote($rlb_note)
    {
        if (is_null($rlb_note)) {
            throw new \InvalidArgumentException('non-nullable rlb_note cannot be null');
        }
        $this->container['rlb_note'] = $rlb_note;

        return $this;
    }

    /**
     * Gets novitax_naplokod
     *
     * @return string|null
     */
    public function getNovitaxNaplokod()
    {
        return $this->container['novitax_naplokod'];
    }

    /**
     * Sets novitax_naplokod
     *
     * @param string|null $novitax_naplokod novitax_naplokod
     *
     * @return self
     */
    public function setNovitaxNaplokod($novitax_naplokod)
    {
        if (is_null($novitax_naplokod)) {
            throw new \InvalidArgumentException('non-nullable novitax_naplokod cannot be null');
        }
        $this->container['novitax_naplokod'] = $novitax_naplokod;

        return $this;
    }

    /**
     * Gets use_gross_values
     *
     * @return bool|null
     */
    public function getUseGrossValues()
    {
        return $this->container['use_gross_values'];
    }

    /**
     * Sets use_gross_values
     *
     * @param bool|null $use_gross_values use_gross_values
     *
     * @return self
     */
    public function setUseGrossValues($use_gross_values)
    {
        if (is_null($use_gross_values)) {
            throw new \InvalidArgumentException('non-nullable use_gross_values cannot be null');
        }
        $this->container['use_gross_values'] = $use_gross_values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


